#!/bin/bash
#copy this file into /etc/init.d/
#update-rc.d curex-fcgi defaults



USER=root
#if not FCGI
DAEMON="/usr/local/bin/us-wallet"
DAEMON_ARGS="-d"
#else
#DAEMON="/usr/bin/spawn-fcgi -p 9000 -n /usr/local/bin/us-wallet -- "
#DAEMON_ARGS="-d -fcgi"
#endif
PIDFILE="/var/run/us-wallet.pid"
NAME="us-wallet"

RETVAL=0

echoret() {
if [ $1 -eq 0 ]; then
	echo "SUCCESS"
else
	echo "FAIL"
fi
}

start() {
      echo -n "Starting us-wallet: "
#     echo "/sbin/start-stop-daemon --quiet --start --background --chuid "$USER" --exec /usr/bin/env $PROG"

/sbin/start-stop-daemon --start  --background -q \
  --pidfile $PIDFILE --make-pidfile \
  --chuid $USER \
  --exec /usr/bin/pipexec -- -k \
  -- [ D $DAEMON $DAEMON_ARGS ] [ L /usr/bin/logger --tag $NAME ] '{D:2>L:0}' '{D:1>L:0}'


      RETVAL=$?
      echoret $RETVAL
}


stop() {
      echo -n "Stopping us-wallet: "
      /sbin/start-stop-daemon -q -o --oknodo --stop --retry --pidfile $PIDFILE 2>/dev/null
      RETVAL=$?
      echoret $RETVAL
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
	sleep 1
      start
  ;;
    *)
      echo "Usage: service us-wallet {start|stop|restart}"
      exit 1
  ;;
esac
ps ax | grep "us-wallet $DAEMON_ARGS" | grep -v grep
exit $RETVAL

