#!/bin/bash


KEYS="$(LD_LIBRARY_PATH=../../gov:/usr/lib ./generate_keys_cpp)"
MESSAGE='blah blah'
LD_LIBRARY_PATH=../../gov:/usr/lib ./test_cpp $KEYS "encrypt" "$MESSAGE"

#call c++ to encrypt
#call java to decrypt
#check

#and other way around
