//------------------file generated by apitool- do not edit
#ifndef USGOV_56573006533bd7c4eca53cd618dca5cfa853c9685c38769d3f79e89cdc9175e9
#define USGOV_56573006533bd7c4eca53cd618dca5cfa853c9685c38769d3f79e89cdc9175e9

#include "wallet_api.h"
#include "pairing_api.h"

namespace us{ namespace wallet {
using namespace std;

struct daemon_api: wallet_api, pairing_api  {
  virtual ~daemon_api() {}
  using wallet_api::priv_t;
  using wallet_api::pub_t;

#include <us/api/apitool_generated__functions_wallet_cpp_purevir>  //APITOOL
#include <us/api/apitool_generated__functions_pairing_cpp_purevir>  //APITOOL

};
}}
#endif
