//------------------file generated by apitool- do not edit
#ifndef USGOV_a8ed513060f3355979cf12e45d55c7d01e80c4163cbd3f3bb5a964805cc18913
#define USGOV_a8ed513060f3355979cf12e45d55c7d01e80c4163cbd3f3bb5a964805cc18913

#include <us/gov/crypto.h>

namespace us{ namespace wallet {
using namespace std;

struct pairing_api {
  typedef us::gov::crypto::ec::keys::pub_t pub_t;
  virtual ~pairing_api() {}

#include <us/api/apitool_generated_pairing_functions_cpp_purevir>

};
}}
#endif
