//------------------file generated by apitool- do not edit
#ifndef US_GOV_WALLET_PAIRING_API_H
#define US_GOV_WALLET_PAIRING_API_H

#include <us/gov/crypto.h>

namespace us{ namespace wallet{
using namespace std;

class pairing_api {
public:
    typedef us::gov::crypto::ec::keys::pub_t pub_t;
    virtual ~pairing_api() {}

    #include <us/api/apitool_generated__functions_pairing_cpp_purevir> //APITOOL
};
}}
#endif
