package us.wallet;

import java.security.PublicKey;
import java.security.PrivateKey;
import java.io.OutputStream;

interface pairing_api {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../api/apitool_generated__functions_pairing_java_purevir
//------------------generated by apitool- do not edit
// pairing - master file: us/apitool/data/pairing
  void pair(String arg0, String arg1, OutputStream os);
  void unpair(String arg0, OutputStream os);
  void list_devices(OutputStream os);
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit
}

