package us.wallet;
import java.io.OutputStream;

public class pairing_rpc_api implements pairing_api {
        pairing_rpc_api(rpc_api endpoint_) {
            endpoint=endpoint_;
        }

//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../api/apitool_generated__functions_pairing_java_rpc-impl
//------------------generated by apitool- do not edit
@Override public void pair(String a0, String a1, OutputStream a2) {
    String o=new String();
    o += a0 + ' ';
    o += a1;
    endpoint.ask(protocol.pairing_pair, o, a2);
}

@Override public void unpair(String a0, OutputStream a1) {
    endpoint.ask(protocol.pairing_unpair, a0, a1);
}

@Override public void list_devices(OutputStream a0) {
    endpoint.ask(protocol.pairing_list_devices, a0);
}

//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit

        rpc_api endpoint;
}



