package us.wallet;

public class protocol {

//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../api/apitool_generated__protocol_wallet-daemon_java
//------------------generated by apitool- do not edit
// wallet - master file: us/apitool/data/wallet
    public static final short wallet_base = 0;
    public static final short wallet_balance = wallet_base+0;
    public static final short wallet_list = wallet_base+2;
    public static final short wallet_new_address = wallet_base+4;
    public static final short wallet_add_address = wallet_base+6;
    public static final short wallet_transfer = wallet_base+8;
    public static final short wallet_tx_make_p2pkh = wallet_base+10;
    public static final short wallet_tx_sign = wallet_base+12;
    public static final short wallet_tx_send = wallet_base+14;
    public static final short wallet_tx_decode = wallet_base+16;
    public static final short wallet_tx_check = wallet_base+18;
    public static final short wallet_ping = wallet_base+20;
// pairing - master file: us/apitool/data/pairing
    public static final short pairing_base = 100;
    public static final short pairing_pair = pairing_base+0;
    public static final short pairing_unpair = pairing_base+2;
    public static final short pairing_list_devices = pairing_base+4;
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit

}

