package us.wallet;
import us.gov.cash.tx.sigcode_t;

//import java.security.PublicKey;
import java.security.PrivateKey;
import java.io.OutputStream;

interface wallet_api {
//---------------------------------------------------------------------generated by make, do not edit
//content of file: ../../api/apitool_generated__functions_wallet_java_purevir
//------------------generated by apitool- do not edit
// wallet - master file: us/apitool/data/wallet
  void balance(boolean arg0, OutputStream os);
  void list(boolean arg0, OutputStream os);
  void new_address(OutputStream os);
  void add_address(String arg0, OutputStream os);
  void transfer(String arg0, long arg1, OutputStream os);
  void tx_make_p2pkh(tx_make_p2pkh_input arg0, OutputStream os);
  void tx_sign(String arg0, sigcode_t arg1, sigcode_t arg2, OutputStream os);
  void tx_send(String arg0, OutputStream os);
  void tx_decode(String arg0, OutputStream os);
  void tx_check(String arg0, OutputStream os);
  void ping(OutputStream os);
//-/----------------generated by apitool- do not edit

//-/-------------------------------------------------------------------generated by make, do not edit
}

