#ifndef USGOV_f7ece82349b5b34e6f48f4dd802ec8765a675855c2e34bc29f2fdc5cc28ed4ba
#define USGOV_f7ece82349b5b34e6f48f4dd802ec8765a675855c2e34bc29f2fdc5cc28ed4ba

#include <stdint.h>
#include <us/gov/socket/protocol.h>

namespace us { namespace gov {
namespace protocol {

#include <us/api/apitool_generated__protocol_gov_id_cpp>
/*
//------------------generated by apitool- do not edit
    static constexpr uint16_t id_base{200};
    static constexpr uint16_t id_request{((id_base+0)<<2)+protocol_suffix};
    static constexpr uint16_t id_peer_challenge{((id_base+1)<<2)+protocol_suffix};
    static constexpr uint16_t id_challenge_response{((id_base+2)<<2)+protocol_suffix};
    static constexpr uint16_t id_peer_status{((id_base+3)<<2)+protocol_suffix};
//------------------generated by apitool- do not edit
//------------------generated by apitool- do not edit
// gov_id - master file: us/apitool/data/gov_id
    static constexpr uint16_t gov_id_base{200};
    static constexpr uint16_t gov_id_request{((gov_id_base+0)<<2)+protocol_suffix};
    static constexpr uint16_t gov_id_peer_challenge{((gov_id_base+1)<<2)+protocol_suffix};
    static constexpr uint16_t gov_id_challenge_response{((gov_id_base+2)<<2)+protocol_suffix};
    static constexpr uint16_t gov_id_peer_status{((gov_id_base+3)<<2)+protocol_suffix};
//-/----------------generated by apitool- do not edit
*/

}
}
}

#endif
