#!/bin/bash

function clean {
	rm -r libs
	rm -r classes
	rm -r test_classes
	rm *.jar
}

function getdeps {
if [ ! -d libs ]; then
mkdir libs
wget http://search.maven.org/remotecontent?filepath=com/madgag/spongycastle/core/1.58.0.0/core-1.58.0.0.jar -O libs/core-1.58.0.0.jar
wget http://search.maven.org/remotecontent?filepath=com/madgag/spongycastle/prov/1.58.0.0/prov-1.58.0.0.jar -O libs/prov-1.58.0.0.jar
wget http://search.maven.org/remotecontent?filepath=com/madgag/spongycastle/pkix/1.54.0.0/pkix-1.54.0.0.jar -O libs/pkix-1.54.0.0.jar
wget http://search.maven.org/remotecontent?filepath=com/madgag/spongycastle/pg/1.54.0.0/pg-1.54.0.0.jar -O libs/pg-1.54.0.0.jar
fi

}

javac=`which javac`
if [ "_$JAVA_HOME" != "_" ]; then
javac=$JAVA_HOME/bin/javac
fi

echo "using javac=$javac"

function source {
	getdeps
	mkdir -p classes
	javac -d classes -cp $libspath src/*.java
	rm -f us-wallet-sdk.jar
	cd classes
	jar cf ../us-wallet-sdk.jar *
	cd ..
}

function all {
	source
	mkdir -p test_classes
	javac -d test_classes -cp $libspath":us-wallet-sdk.jar" tests/*.java
	rm -f us-test-sdk.jar
	cd test_classes
	jar cf ../us-test-sdk.jar *
	cd ..
}



cmd=$1
libspath="libs/core-1.58.0.0.jar:libs/pg-1.54.0.0.jar:libs/pkix-1.54.0.0.jar:libs/prov-1.58.0.0.jar"


if [ "_$cmd" == "_" ]; then
	cmd="all"
fi

if [ "_$cmd" == "_all" ]; then
	all
fi

if [ "_$cmd" == "_source" ]; then
	source
fi

if [ "_$cmd" == "_clean" ]; then
	clean
fi


