//content of file: api/apitool_generated__protocol_gov_socket_java
//------------------generated by apitool- do not edit
// gov_socket - master file: us/apitool/data/gov_socket
    public static final short protocol_gov_socket_base = 100;
    public static final short protocol_gov_socket_error = ((protocol_gov_socket_base+0)<<2)+protocol_suffix;
    public static final short protocol_gov_socket_ping = ((protocol_gov_socket_base+1)<<2)+protocol_suffix;
    public static final short protocol_gov_socket_pong = ((protocol_gov_socket_base+2)<<2)+protocol_suffix;
//-/----------------generated by apitool- do not edit

