#!/bin/bash
#copy this file into /etc/init.d/
#update-rc.d curex-fcgi defaults

USER=root

DAEMON="/usr/local/bin/us-gov"
DAEMON_ARGS="-ds"
PIDFILE="/var/run/us-gov.pid"
NAME="us-gov"

RETVAL=0

echoret() {
if [ $1 -eq 0 ]; then
	echo "SUCCESS"
else
	echo "FAIL"
fi
}


start() {
      echo -n "Starting us-gov: "
# 	  echo "/sbin/start-stop-daemon --quiet --start --background --chuid "$USER" --exec /usr/bin/env $PROG"

/sbin/start-stop-daemon --start  --background -o -q  --pidfile $PIDFILE --make-pidfile  --chuid $USER  --startas /usr/bin/pipexec -- -k  -- [ D $DAEMON $DAEMON_ARGS ] [ L /usr/bin/logger --tag $NAME ] '{D:2>L:0}' 

# '{D:1>L:0}'

      RETVAL=$?
      echoret $RETVAL
}

stop() {
      echo -n "Stopping us-gov: "
      /sbin/start-stop-daemon -q -o --stop --pidfile $PIDFILE 2>/dev/null

      RETVAL=$?
      echoret $RETVAL
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
	sleep 1
      start
  ;;
    *)
      echo "Usage: us-gov {start|stop|restart}"
      exit 1
  ;;
esac
ps ax | grep "us-gov $DAEMON_ARGS" | grep -v grep
exit $RETVAL

