#!/bin/bash
#copy this file into /etc/init.d/
#update-rc.d curex-fcgi defaults

USER=root

DAEMON="/usr/local/bin/us-gov"
DAEMON_ARGS="-ds"
PIDFILE="/var/run/us-gov.pid"
NAME="us-gov"

RETVAL=0

start() {
      echo -n "Starting us-gov: "
      /sbin/start-stop-daemon --start  --background -o -q  --no-close  --pidfile $PIDFILE --make-pidfile  --chuid $USER  --startas /usr/bin/pipexec -- -k -l 2 -- [ D $DAEMON $DAEMON_ARGS ] [ L /usr/bin/logger --tag $NAME ] "{D:2>D:1}" "{D:1>L:0}"
      RETVAL=$?
}

stop() {

      echo -n "Stopping us-gov: "
      /sbin/start-stop-daemon -q -o --stop --retry 2 --pidfile $PIDFILE

      RETVAL=$?
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
      start
  ;;
    *)
      echo "Usage: us-gov {start|stop|restart}"
      exit 1
  ;;
esac
echo "$RETVAL"
exit $RETVAL

