#!/bin/bash
#copy this file into /etc/init.d/
#update-rc.d curex-fcgi defaults

USER=root

DAEMON="/usr/local/bin/us-govd"
DAEMON_ARGS="-ds"
PIDFILE="/var/run/us-govd.pid"
NAME="us-govd"

RETVAL=0

start() {
      echo -n "Starting us-gov: "
# 	  echo "/sbin/start-stop-daemon --quiet --start --background --chuid "$USER" --exec /usr/bin/env $PROG"
  #    /sbin/start-stop-daemon  --start --background --chuid "$USER" --exec /usr/bin/env  $PROG > /var/log/us-govd.log 2>&1

/sbin/start-stop-daemon --start  --background \
  --pidfile $PIDFILE --make-pidfile \
  --chuid $USER \
  --startas /usr/bin/pipexec -- -k \
   -- [ D $DAEMON $DAEMON_ARGS ] [ L /usr/bin/logger --tag $NAME ] '{D:2>D:1}' '{D:1>L:0}'


      RETVAL=$?
      echo "$API_NAME. $RETVAL"
}

stop() {
      echo -n "Stopping us-gov: "
      killall -q -w -u $USER us-govd
      RETVAL=$?
      echo "$API_NAME. $RETVAL"
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
      start
  ;;
    *)
      echo "Usage: us-gov {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL

