#!/bin/bash
#copy this file into /etc/init.d/
#update-rc.d curex-fcgi defaults

USER=root
DAEMON="/usr/local/bin/us-wallet"  #D; INSTALLER will tweak this line
DAEMON_ARGS="-d"                   #A; INSTALLER will tweak this line

PIDFILE="/var/run/us-wallet.pid"
NAME="us-wallet"

RETVAL=0

start() {
      echo -n "Starting us-wallet: "
#     echo "/sbin/start-stop-daemon --quiet --start --background --chuid "$USER" --exec /usr/bin/env $PROG"

/sbin/start-stop-daemon --start  --background \
  --pidfile $PIDFILE --make-pidfile \
  --chuid $USER \
  --startas /usr/bin/pipexec -- -k \
  -- [ D $DAEMON $DAEMON_ARGS ] [ L /usr/bin/logger --tag $NAME ] '{D:2>L:0}' '{D:1>L:0}'


      RETVAL=$?
      echo "$API_NAME. $RETVAL"
}


stop() {

      echo -n "Stopping us-wallet: "
      /sbin/start-stop-daemon -q -o --oknodo --stop --retry --pidfile $PIDFILE 2>/dev/null
      RETVAL=$?
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
      start
  ;;
    *)
      echo "Usage: service us-wallet {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL

