/*

   public static final short wallet_base = 0;
    public static final short protocol_balance_query = wallet_base+1;
    public static final short protocol_dump_query = wallet_base+2;
    public static final short protocol_new_address_query = wallet_base+3;
    public static final short protocol_add_address_query = wallet_base+4;
    public static final short protocol_tx_make_p2pkh_query = wallet_base+5;
    public static final short protocol_tx_sign_query = wallet_base+6;
    public static final short protocol_tx_send_query = wallet_base+7;
    public static final short protocol_tx_decode_query = wallet_base+8;
    public static final short protocol_tx_check_query = wallet_base+9;
    public static final short protocol_pair_query = wallet_base+10;
    public static final short protocol_unpair_query = wallet_base+11;
    public static final short protocol_list_devices_query = wallet_base+12;

    public static final short protocol_response = wallet_base+0;
*/

#include <iostream>
#include <vector>
using namespace std;


void gen_cpp(const vector<string>& v, ostream& os) {
    os << "//------------------generated by apitool- do not edit" << endl;
    int n=0;
    const string& base=v[0];
    os << "    static constexpr uint16_t " << v[n++] << "{0};" << endl;
    for (;n<v.size();++n) {
        os << "    static constexpr uint16_t " << v[n] << "{" << base << "+" << n << "};" << endl;
    }
    os << "//------------------generated by apitool- do not edit" << endl;
}


void gen_java(const vector<string>& v, ostream& os) {
    os << "//------------------generated by apitool- do not edit" << endl;
    int n=0;
    const string& base=v[0];
    os << "    public static final short " << v[n++] << " = 0;" << endl;
    for (;n<v.size();++n) {
        os << "    public static final short protocol_" << v[n] << " = " << base << "+" << n << ";" << endl;
    }
    os << "//------------------generated by apitool- do not edit" << endl;
}


void gen_gov_cpp(int mbase, const vector<string>& v, ostream& os) {
    os << "//------------------generated by apitool- do not edit" << endl;
    int n=0;
    const string& base=v[0];
    os << "    static constexpr uint16_t " << v[n++] << "{" << mbase << "};" << endl;
    for (;n<v.size();++n) {
        os << "    static constexpr uint16_t " << v[n] << "{((" << base << "+" << n-1 << ")<<2)+protocol_suffix};" << endl;
    }
    os << "//------------------generated by apitool- do not edit" << endl;
}
void gen_gov_java(int mbase, const vector<string>& v, ostream& os) {
    os << "//------------------generated by apitool- do not edit" << endl;
    int n=0;
    const string& base=v[0];
    os << "    public static final short gov_" << v[n++] << " = " << mbase << ";" << endl;
    for (;n<v.size();++n) {
        os << "    public static final short gov_" << v[n] << " = ((gov_" << base << "+" << n-1 << ")<<2)+protocol_suffix;" << endl;
    }
    os << "//------------------generated by apitool- do not edit" << endl;
}

void gen_gov(int base, const vector<string>& v, ostream& os) {
    cout << "C++" << endl;
    gen_gov_cpp(base,v,os);
    cout << "files affected:" << endl;
    cout << "  gov/id/protocol.h" << endl;
    cout << endl;

    cout << "java" << endl;

    gen_gov_java(base,v,os);
    cout << "files affected:" << endl;
    cout << "  sdk/java/src/wallet.h" << endl;
    cout << endl;

}

int main() {

vector<string> f{ "wallet_base","balance_query","list_query",
    "new_address_query","add_address_query","tx_make_p2pkh_query",
    "tx_sign_query","tx_send_query","tx_decode_query",
    "tx_check_query","pair_query","unpair_query","list_devices_query",
    "ping","response" };


vector<string> gov_id{
    "id_base",
    "id_request",
    "id_peer_challenge",
    "id_challenge_response",
    "id_peer_status"
};


    cout << "-------------wallet" << endl;
   
    cout << "C++" << endl;
    gen_cpp(f,cout);
    cout << "files affected:" << endl;
    cout << "  wallet/protocol.h" << endl;
    cout << endl;

    cout << "java" << endl;
    gen_java(f,cout);
    cout << "files affected:" << endl;
    cout << "  sdk/java/src/Wallet.java" << endl;


    cout << "-------------gov" << endl;
    cout << "" << endl;
    cout << "-------------gov::id" << endl;
    gen_gov(200,gov_id,cout);

    return 0;
}
